export const content = {
  en: {
    nav: {
      home: "Home",
      about: "About Us",
      products: "Products",
      quality: "Quality",
      facilities: "Facilities",
      contact: "Contact",
      callUs: "Call Us",
    },
    hero: {
      tagline: "Animal Feed Manufacturing Since 2058 BS",
      title: "Buddha Dana Udhyog Pvt. Ltd.",
      subtitle: "Supporting better livestock and poultry nutrition through dependable feed solutions from the heart of Nepal.",
      cta1: "Explore Products",
      cta2: "Contact Us",
    },
    aboutPreview: {
      heading: "About Our Company",
      description: "Buddha Dana Udhyog Pvt. Ltd. is a Nepalese animal feed manufacturing company with roots going back to 2058 BS. With our production plant established in 2072 BS, we have been dedicated to producing quality feed for livestock and poultry across Nepal.",
      foundedLabel: "Founded",
      plantLabel: "Plant Established",
      cta: "Learn More About Us",
    },
    products: {
      heading: "Our Products",
      subtitle: "Quality feed solutions for livestock and poultry",
      description: "We produce a range of animal feed products designed to support healthy growth and productivity. Each product reflects our commitment to quality and consistency.",
      cta: "View All Products",
    },
    timeline: {
      heading: "Our Journey",
      subtitle: "Key milestones in our company's history",
      milestone1Year: "2058 BS",
      milestone1Text: "Buddha Dana Udhyog Pvt. Ltd. was founded with a vision to contribute to Nepal's agricultural sector through quality animal feed.",
      milestone2Year: "2072 BS",
      milestone2Text: "Our production plant was established, marking a significant step in our ability to serve farmers and livestock owners across Nepal.",
    },
    leadership: {
      heading: "Our Leadership",
      subtitle: "Guided by experienced directors committed to quality and integrity",
    },
    quality: {
      heading: "Quality & Manufacturing",
      subtitle: "Our commitment to dependable feed production",
      description: "At Buddha Dana Udhyog, quality is at the heart of everything we do. Our manufacturing processes are built on principles of consistency, responsibility, and operational discipline. We believe that dependable feed starts with dependable practices.",
      values: [
        { title: "Consistency", description: "Every batch of feed meets the same standards our customers expect." },
        { title: "Responsibility", description: "We take our role in the food chain seriously, from raw materials to finished product." },
        { title: "Discipline", description: "Our operations follow structured processes that ensure reliability." },
        { title: "Care", description: "We understand that our feed directly impacts the health of animals and livelihoods of farmers." },
      ],
    },
    facilities: {
      heading: "Our Facilities",
      subtitle: "Where quality feed is produced",
      description: "Our production facility in Siyari-05, Banghusari represents our commitment to manufacturing excellence. The plant is designed to produce consistent, quality animal feed for the Nepalese market.",
      note: "Photographs of our facility will be added soon.",
    },
    contact: {
      heading: "Get In Touch",
      subtitle: "We'd be happy to hear from you",
      companyName: "Buddha Dana Udhyog Pvt. Ltd.",
      address: "Siyari-05, Banghusari, Nepal",
      call: "Call",
      email: "Email Us",
      maps: "Open in Google Maps",
      hours: "Business Hours",
      hoursText: "Sunday - Friday: 9:00 AM - 5:00 PM",
    },
    footer: {
      tagline: "Quality animal feed manufacturing from the heart of Nepal.",
      quickLinks: "Quick Links",
      contactInfo: "Contact Info",
      location: "Location",
      copyright: "© 2024 Buddha Dana Udhyog Pvt. Ltd. All rights reserved.",
    },
    notFound: {
      title: "Page Not Found",
      description: "The page you're looking for doesn't exist or has been moved.",
      cta: "Return Home",
    },
  },
  ne: {
    nav: {
      home: "गृहपृष्ठ",
      about: "हाम्रो बारेमा",
      products: "उत्पादनहरू",
      quality: "गुणस्तर",
      facilities: "सुविधाहरू",
      contact: "सम्पर्क",
      callUs: "कल गर्नुहोस्",
    },
    hero: {
      tagline: "२०५८ बि.सं. देखि पशु आहार उत्पादन",
      title: "बुद्ध दान उद्योग प्रा. लि.",
      subtitle: "नेपालको मुटुबाट भरपर्दो आहार समाधान मार्फत पशुधन र कुखुरा पोषणलाई सहयोग गर्दै।",
      cta1: "उत्पादनहरू हेर्नुहोस्",
      cta2: "सम्पर्क गर्नुहोस्",
    },
    aboutPreview: {
      heading: "हाम्रो कम्पनीको बारेमा",
      description: "बुद्ध दान उद्योग प्रा. लि. एक नेपाली पशु आहार उत्पादन कम्पनी हो जसको इतिहास २०५८ बि.सं. देखि सुरु भएको हो। २०७२ बि.सं. मा हाम्रो उत्पादन प्लान्ट स्थापना भयो, त्यसयता हामी नेपालभरका पशुधन र कुखुराको लागि गुणस्तरीय आहार उत्पादनमा समर्पित छौं।",
      foundedLabel: "स्थापना",
      plantLabel: "प्लान्ट स्थापना",
      cta: "हाम्रो बारेमा थप जान्नुहोस्",
    },
    products: {
      heading: "हाम्रा उत्पादनहरू",
      subtitle: "पशुधन र कुखुराको लागि गुणस्तरीय आहार समाधान",
      description: "हामी पशु आहारका विभिन्न उत्पादनहरू उत्पादन गर्छौं जुन स्वस्थ वृद्धि र उत्पादकत्वलाई सहयोग गर्न डिजाइन गरिएका छन्। प्रत्येक उत्पादनले गुणस्तर र स्थिरताप्रतिको हाम्रो प्रतिबद्धतालाई प्रतिबिम्बित गर्दछ।",
      cta: "सबै उत्पादनहरू हेर्नुहोस्",
    },
    timeline: {
      heading: "हाम्रो यात्रा",
      subtitle: "हाम्रो कम्पनीको इतिहासका प्रमुख मोहरहरू",
      milestone1Year: "२०५८ बि.सं.",
      milestone1Text: "बुद्ध दान उद्योग प्रा. लि. को स्थापना गुणस्तरीय पशु आहार मार्फत नेपालको कृषि क्षेत्रमा योगदान पुर्‍याउने दृष्टिकोणसहित गरिएको थियो।",
      milestone2Year: "२०७२ बि.सं.",
      milestone2Text: "हाम्रो उत्पादन प्लान्ट स्थापना भयो, जसले नेपालभरका किसान र पशुधन मालिकहरूलाई सेवा प्रदान गर्ने हाम्रो क्षमतामा महत्त्वपूर्ण कदम चिह्नित गर्यो।",
    },
    leadership: {
      heading: "हाम्रो नेतृत्व",
      subtitle: "गुणस्तर र इमान्डारिताप्रति प्रतिबद्ध अनुभवी निर्देशकहरूद्वारा संचालित",
    },
    quality: {
      heading: "गुणस्तर र उत्पादन",
      subtitle: "भरपर्दो आहार उत्पादनप्रतिको हाम्रो प्रतिबद्धता",
      description: "बुद्ध दान उद्योगमा, गुणस्तर हामीले गर्ने हरेक कुराको केन्द्रमा छ। हाम्रा उत्पादन प्रक्रियाहरू स्थिरता, जिम्मेवारी र सञ्चालन अनुशासनका सिद्धान्तहरूमा आधारित छन्। हामी विश्वास गर्छौं कि भरपर्दो आहार भरपर्दो अभ्यासबाट सुरु हुन्छ।",
      values: [
        { title: "स्थिरता", description: "आहारको प्रत्येक ब्याचले हाम्रा ग्राहकहरूले अपेक्षा गर्ने एउटै मापदण्ड पूरा गर्दछ।" },
        { title: "जिम्मेवारी", description: "हामी कच्चा पदार्थदेखि तयार उत्पादनसम्म खाद्य श्रृङ्खलामा हाम्रो भूमिकालाई गम्भीरतापूर्वक लिन्छौं।" },
        { title: "अनुशासन", description: "हाम्रा सञ्चालनहरूले विश्वसनीयता सुनिश्चित गर्ने संरचित प्रक्रियाहरू अनुसरण गर्दछन्।" },
        { title: "हेरचाह", description: "हामी बुझ्छौं कि हाम्रो आहारले प्रत्यक्ष रूपमा पशुहरूको स्वास्थ्य र किसानहरूको जीविकोपार्जनलाई असर गर्दछ।" },
      ],
    },
    facilities: {
      heading: "हाम्रा सुविधाहरू",
      subtitle: "जहाँ गुणस्तरीय आहार उत्पादन हुन्छ",
      description: "सियारी-०५, बाङ्गुसारीमा रहेको हाम्रो उत्पादन सुविधाले उत्पादन उत्कृष्टताप्रतिको हाम्रो प्रतिबद्धतालाई जनाउँछ। यो प्लान्ट नेपाली बजारको लागि स्थिर, गुणस्तरीय पशु आहार उत्पादन गर्न डिजाइन गरिएको छ।",
      note: "हाम्रो सुविधाका फोटोहरू चाँडै थपिनेछ।",
    },
    contact: {
      heading: "सम्पर्क गर्नुहोस्",
      subtitle: "हामी तपाईंबाट सुन्न पाउँदा खुशी हुनेछौं",
      companyName: "बुद्ध दान उद्योग प्रा. लि.",
      address: "सियारी-०५, बाङ्गुसारी, नेपाल",
      call: "कल गर्नुहोस्",
      email: "इमेल गर्नुहोस्",
      maps: "गुगल म्याप्समा खोल्नुहोस्",
      hours: "कार्यालय समय",
      hoursText: "आइतबार - शुक्रबार: बिहान ९:०० - साँझ ५:००",
    },
    footer: {
      tagline: "नेपालको मुटुबाट गुणस्तरीय पशु आहार उत्पादन।",
      quickLinks: "द्रुत लिङ्कहरू",
      contactInfo: "सम्पर्क जानकारी",
      location: "स्थान",
      copyright: "© २०२४ बुद्ध दान उद्योग प्रा. लि. सर्वाधिकार सुरक्षित।",
    },
    notFound: {
      title: "पृष्ठ फेला परेन",
      description: "तपाईंले खोज्नुभएको पृष्ठ अवस्थित छैन वा सारिएको छ।",
      cta: "गृहपृष्ठमा फर्कनुहोस्",
    },
  },
};

export type Content = typeof content.en;
